[build]
    command = "GATSBY_CONCURRENT_DOWNLOAD=25 yarn workspace engine build"
  	functions = "engine/src/api"
    publish = "engine/public"

[build.environment]
  NODE_VERSION = "18.12.1"

[[plugins]]
  package = "@netlify/plugin-gatsby"

[[plugins]]
  package = "@netlify/plugin-local-install-core"
